name: Frontend Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"
env:
  IMAGE_TAG: ${{ github.sha }}
  FRONTEND_REPOSITORY: labs-dvn-repo/dev/frontend
permissions:
  id-token: write 
  contents: read 
jobs:
  frontend:
    name: Frontend Jobs
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: ${{vars.AWS_REGION}}
          role-to-assume: ${{vars.AWS_ROLE_TO_ASSUME_ARN}}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Npm install
        working-directory: apps/frontend/youtube-live-app
        run: |
          npm ci --silent 
      - name: Npm build
        working-directory: apps/frontend/youtube-live-app
        run: |
          npm run build --silent
      - name: Upload to S3
        working-directory: apps/frontend/youtube-live-app
        run: |
          aws s3 sync ./out ${{vars.AWS_S3_BUCKET}}
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{vars.AWS_CLOUDFRONT_DISTRIBUITION}} --paths "/*"
    
      